model:
  expansion_factor: 16
  l1_coeff: 5
  loss_type: "l1"

training:
  llm_batch_size: 32
  sae_batch_size: 4096
  lr: 0.0003
  weight_decay: 0.01
  num_warmup_steps: 1000
  max_length: 512
  num_epochs: 1
  dataset_path: "CohereForAI/aya_dataset"
  device: "cuda"
  
  llm_path: "Qwen/Qwen2.5-1.5B" 
  target_layer_name: "model.layers.20" 
  max_size: 500000