training:
  llm_path: "google/gemma-2-2b"
  dataset_path: "CohereForAI/aya_dataset"
  target_layer_names: [
    "model.layers.2",
    "model.layers.12",
    "model.layers.20"
  ]
  device: "cuda"
  repo_id: "ilyas-17/gemma-2b-multilingual-saes"

  model:
    d_sae: 16384
    l1_coeff: [5.0, 10.0, 20.0]
    loss_type: "l1"

  optim:
    llm_batch_size: 256
    sae_batch_size: 4096
    lr: 0.0005
    weight_decay: 0.0
    num_warmup_steps: 2000
    max_length: 512
    num_epochs: 1
    max_size: 500000

analyse:
  llm_path: "google/gemma-2-2b"
  sae_repo_id: "google/gemma-scope-2b-pt-res"
  num_layers: 26
  layers: [] # Vide pour faire toutes les couches
  device: "cuda"
  sae_type: "gemma_scope" 
  custom_checkpoint_path: "./sae_weights.pt"
  custom_d_sae: 16384
  
  extract:
    dataset_path: "./data/multilingual_rare.jsonl"
    top_k: 5
    batch_size: 32
    max_length: 128
    
  code_switch:
    dataset_path: "./data/forced_code_switch.jsonl"
    balanced_dataset_path: "data/v2_balanced_code_switch.jsonl"
    target_languages: ["en", "fr", "es", "ko", "ja", "pt", "vi", "th", "zh"]
    source_languages: ["en", "fr", "es", "ko", "ja", "pt", "vi", "th", "zh"]
    or_language: "en" 
    batch_size: 16

  ablation:
    dataset_path: "./data/multilingual_rare.jsonl"
    top_features_file: "top_features_gemma_scope.json"
    target_languages: ['pan', 'guj', 'arb', 'vie', 'sin', 'tel', 'zsm', 'som', 'tam', 'yor']
    max_samples_per_language: 500
    batch_size: 16
    feature_configs: [[0, 1], [1, 1], [0, 2]]